# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created: Thu Jul 12 20:56:25 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Table(object):
    def setupUi(self, Table):
        Table.setObjectName(_fromUtf8("Table"))
        Table.resize(958, 249)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Table.sizePolicy().hasHeightForWidth())
        Table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        Table.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/gtk-execute.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Table.setWindowIcon(icon)
        Table.setFlat(False)
        Table.setCheckable(False)
        Table.setChecked(False)
        self.gridLayout_2 = QtGui.QGridLayout(Table)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TableWidget = QtGui.QTableWidget(Table)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget.sizePolicy().hasHeightForWidth())
        self.TableWidget.setSizePolicy(sizePolicy)
        self.TableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.TableWidget.setToolTip(_fromUtf8(""))
        self.TableWidget.setAutoFillBackground(False)
        self.TableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.TableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.TableWidget.setLineWidth(1)
        self.TableWidget.setMidLineWidth(1)
        self.TableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableWidget.setAutoScroll(True)
        self.TableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.TableWidget.setTabKeyNavigation(False)
        self.TableWidget.setDragEnabled(True)
        self.TableWidget.setDragDropOverwriteMode(False)
        self.TableWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.TableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.TableWidget.setAlternatingRowColors(True)
        self.TableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.TableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.TableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.TableWidget.setShowGrid(True)
        self.TableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.TableWidget.setObjectName(_fromUtf8("TableWidget"))
        self.TableWidget.setColumnCount(9)
        self.TableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.TableWidget.setItem(0, 0, item)
        self.TableWidget.horizontalHeader().setVisible(True)
        self.TableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.TableWidget.horizontalHeader().setHighlightSections(True)
        self.TableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.TableWidget.horizontalHeader().setStretchLastSection(True)
        self.TableWidget.verticalHeader().setVisible(True)
        self.TableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.TableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        Table.setWindowTitle(QtGui.QApplication.translate("Table", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        Table.setTitle(QtGui.QApplication.translate("Table", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.TableWidget.setSortingEnabled(False)
        item = self.TableWidget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Table", "m1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Table", "m5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Table", "m30", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Table", "h1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Table", "h4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Table", "d1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Table", "candle", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Table", "last zone", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Table", "closest zone", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Table", "ajctr", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Table", "apaor", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Table", "str", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Table", "fvb", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Table", "vtr", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableWidget.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Table", "confirmation", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.TableWidget.isSortingEnabled()
        self.TableWidget.setSortingEnabled(False)
        self.TableWidget.setSortingEnabled(__sortingEnabled)

from . import elementary_rc
